"""Vault writer with managed-section idempotency (architecture.md KTD-7 mechanism).

Layout of every generated note:

    ---
    <generated frontmatter, incl. content_hash of the managed region>
    ---
    <manual text here survives re-runs>
    <!-- ri:begin main -->
    <AI-managed content>
    <!-- ri:end main -->
    <manual text here survives re-runs>

Rules enforced here:
- unchanged input -> byte-for-byte no-op
- out-of-marker manual edits preserved verbatim; a .bak lands in .ri-backups/ before
  any file containing manual edits is rewritten
- unbalanced/corrupted markers -> file treated as fully manual: skip rewrite, warn,
  still write the .bak (conservative fallback)
- backups capped at the 10 most recent per source file"""

from __future__ import annotations

import hashlib
import logging
import re
from datetime import UTC, datetime
from pathlib import Path

from relationship_intel.util.markdown import frontmatter_block

logger = logging.getLogger(__name__)

BEGIN = "<!-- ri:begin main -->"
END = "<!-- ri:end main -->"
BACKUP_KEEP = 10

_FM_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)


def managed_hash(managed: str) -> str:
    return hashlib.sha256(managed.encode("utf-8")).hexdigest()[:16]


class VaultWriter:
    def __init__(self, vault_root: str | Path):
        self.root = Path(vault_root) / "relationship-intelligence"

    def path_for(self, folder: str, note_name: str) -> Path:
        return self.root / folder / f"{note_name}.md"

    def write_note(
        self,
        folder: str,
        note_name: str,
        frontmatter: list[tuple[str, object]],
        managed: str,
    ) -> Path:
        path = self.path_for(folder, note_name)
        path.parent.mkdir(parents=True, exist_ok=True)

        frontmatter = frontmatter + [("content_hash", managed_hash(managed))]
        rendered_fm = frontmatter_block(frontmatter)

        if not path.exists():
            path.write_text(f"{rendered_fm}\n{BEGIN}\n{managed}\n{END}\n", encoding="utf-8")
            return path

        existing = path.read_text(encoding="utf-8")
        begin_count, end_count = existing.count(BEGIN), existing.count(END)
        if begin_count != 1 or end_count != 1 or existing.index(BEGIN) > existing.index(END):
            logger.warning(
                "Unbalanced ri: markers in %s — treating as fully manual, skipping rewrite",
                path,
            )
            self._backup(path, existing)
            return path

        pre_all, rest = existing.split(BEGIN, 1)
        old_managed, post = rest.split(END, 1)
        old_managed = old_managed.strip("\n")
        fm_match = _FM_RE.match(pre_all)
        pre = pre_all[fm_match.end() :] if fm_match else pre_all
        old_hash = _stored_hash(fm_match.group(0)) if fm_match else None

        candidate = f"{rendered_fm}\n{pre}{BEGIN}\n{managed}\n{END}{post}"
        if candidate == existing:
            return path

        manually_edited = (
            bool(pre.strip())
            or bool(post.strip())
            or (old_hash is not None and managed_hash(old_managed) != old_hash)
        )
        if manually_edited:
            self._backup(path, existing)
        path.write_text(candidate, encoding="utf-8")
        return path

    def _backup(self, path: Path, content: str) -> None:
        rel = path.relative_to(self.root)
        backup_dir = self.root / ".ri-backups" / rel.parent / rel.stem
        backup_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S%f")
        (backup_dir / f"{stamp}.md").write_text(content, encoding="utf-8")
        backups = sorted(backup_dir.glob("*.md"))
        for old in backups[:-BACKUP_KEEP]:
            old.unlink()

    def write_jsonl_index(self, name: str, lines: list[str]) -> Path:
        path = self.root / "indexes" / f"{name}.jsonl"
        path.parent.mkdir(parents=True, exist_ok=True)
        content = "\n".join(lines) + ("\n" if lines else "")
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
        return path

    def write_report(self, filename: str, content: str) -> Path:
        path = self.root / "reports" / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
        return path

    def ensure_readme(self) -> None:
        path = self.root / "README.md"
        if path.exists():
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Relationship Intelligence Archive\n\n"
            "Generated by the SM-CRM-System pipeline (evidence layer — the CRM holds\n"
            "operational summaries only). AI-managed content lives between\n"
            "`<!-- ri:begin main -->` / `<!-- ri:end main -->` markers; anything you\n"
            "write outside the markers survives re-runs. Notes default to\n"
            "`review_status: unreviewed` until a human reviews them (ORD-0003).\n",
            encoding="utf-8",
        )


def _stored_hash(frontmatter_text: str) -> str | None:
    for line in frontmatter_text.splitlines():
        if line.startswith("content_hash:"):
            return line.split(":", 1)[1].strip()
    return None
